### ISSUE TITLE
Native library is out of date

### ISSUE THREAD

**Issue by ghost** [intel-iot-devkit/tinyb#141]
I'm experiencing the same issue as the following: https://github.com/intel-iot-devkit/tinyb/issues/46

When I try to execute a simple java class that just calls manager.startDiscovery() I get the following error: 

**Exception in thread "main" java.lang.RuntimeException: Native library is out of date. Please update the native library.
	at tinyb.BluetoothManager.getBluetoothManager(BluetoothManager.java:317)**

Here's my classpath:
/usr/java/jdk1.8.0_152/jre/lib/charsets.jar:/usr/java/jdk1.8.0_152/jre/lib/deploy.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/cldrdata.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/dnsns.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/jaccess.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/jfxrt.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/localedata.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/nashorn.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/sunec.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/sunjce_provider.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/sunpkcs11.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/zipfs.jar:/usr/java/jdk1.8.0_152/jre/lib/javaws.jar:/usr/java/jdk1.8.0_152/jre/lib/jce.jar:/usr/java/jdk1.8.0_152/jre/lib/jfr.jar:/usr/java/jdk1.8.0_152/jre/lib/jfxswt.jar:/usr/java/jdk1.8.0_152/jre/lib/jsse.jar:/usr/java/jdk1.8.0_152/jre/lib/management-agent.jar:/usr/java/jdk1.8.0_152/jre/lib/plugin.jar:/usr/java/jdk1.8.0_152/jre/lib/resources.jar:/usr/java/jdk1.8.0_152/jre/lib/rt.jar:/home/sj/projects/code/yeelightbedside/target/classes:/home/sj/.m2/repository/org/sputnikdev/bluetooth-manager-tinyb/1.2/bluetooth-manager-tinyb-1.2.jar:/home/sj/.m2/repository/org/sputnikdev/bluetooth-manager/1.3/bluetooth-manager-1.3.jar:/home/sj/.m2/repository/org/sputnikdev/bluetooth-utils/1.9/bluetooth-utils-1.9.jar:/home/sj/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar:/home/sj/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/home/sj/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar:/home/sj/projects/code/yeelightbedside/src/main/lib/tinyb.jar 

The output of the build & install is as follows:
**[sj@Eire build]$ cmake ..**
INFO - libtinyb Version v0.5.1
-- JNI_INCLUDE_DIRS=/usr/java/jdk1.8.0_152/include;/usr/java/jdk1.8.0_152/include/linux;/usr/java/jdk1.8.0_152/include
-- JNI_LIBRARIES=/usr/java/jdk1.8.0_152/jre/lib/amd64/libjawt.so;/usr/java/jdk1.8.0_152/jre/lib/amd64/server/libjvm.so
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sj/projects/tools/tinyb/build
**[sj@Eire build]$ make**
[  2%] Building Java objects for tinybjar.jar
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
[  4%] Generating CMakeFiles/tinybjar.dir/java_class_filelist
[  6%] Creating Java archive tinyb.jar
Generating JNI headers..

Warning: The javah tool is planned to be removed in the next major
JDK release. The tool has been superseded by the '-h' option added
to javac in JDK 8. Users are recommended to migrate to using the
javac '-h' option; see the javac man page for more information.

[  6%] Built target tinybjar
[  8%] Building CXX object src/CMakeFiles/tinyb.dir/BluetoothObject.cpp.o
[ 10%] Building CXX object src/CMakeFiles/tinyb.dir/BluetoothEvent.cpp.o
[ 12%] Building CXX object src/CMakeFiles/tinyb.dir/BluetoothManager.cpp.o
[ 14%] Building CXX object src/CMakeFiles/tinyb.dir/BluetoothAdapter.cpp.o
[ 16%] Building CXX object src/CMakeFiles/tinyb.dir/BluetoothDevice.cpp.o
[ 18%] Building CXX object src/CMakeFiles/tinyb.dir/BluetoothGattService.cpp.o
[ 20%] Building CXX object src/CMakeFiles/tinyb.dir/BluetoothGattCharacteristic.cpp.o
[ 22%] Building CXX object src/CMakeFiles/tinyb.dir/BluetoothGattDescriptor.cpp.o
[ 24%] Building CXX object src/CMakeFiles/tinyb.dir/BluetoothUUID.cpp.o
[ 26%] Building CXX object src/CMakeFiles/tinyb.dir/tinyb_utils.cpp.o
[ 28%] Building C object src/CMakeFiles/tinyb.dir/generated-code.c.o
[ 30%] Building C object src/CMakeFiles/tinyb.dir/version.c.o
[ 32%] Linking CXX shared library libtinyb.so
[ 32%] Built target tinyb
[ 34%] Building CXX object java/jni/CMakeFiles/javatinyb.dir/BluetoothAdapter.cxx.o
[ 36%] Building CXX object java/jni/CMakeFiles/javatinyb.dir/BluetoothDevice.cxx.o
[ 38%] Building CXX object java/jni/CMakeFiles/javatinyb.dir/BluetoothEvent.cxx.o
[ 40%] Building CXX object java/jni/CMakeFiles/javatinyb.dir/BluetoothGattCharacteristic.cxx.o
[ 42%] Building CXX object java/jni/CMakeFiles/javatinyb.dir/BluetoothGattDescriptor.cxx.o
[ 44%] Building CXX object java/jni/CMakeFiles/javatinyb.dir/BluetoothGattService.cxx.o
[ 46%] Building CXX object java/jni/CMakeFiles/javatinyb.dir/BluetoothManager.cxx.o
[ 48%] Building CXX object java/jni/CMakeFiles/javatinyb.dir/BluetoothObject.cxx.o
[ 50%] Building CXX object java/jni/CMakeFiles/javatinyb.dir/JNIMem.cxx.o
/home/sj/projects/tools/tinyb/java/jni/JNIMem.cxx: In function ‘jint JNI_OnLoad(JavaVM*, void*)’:
/home/sj/projects/tools/tinyb/java/jni/JNIMem.cxx:30:39: warning: unused parameter ‘reserved’ [-Wunused-parameter]
 jint JNI_OnLoad(JavaVM *initVM, void *reserved) {
                                       ^~~~~~~~
[ 52%] Building CXX object java/jni/CMakeFiles/javatinyb.dir/helper.cxx.o
[ 54%] Linking CXX shared library libjavatinyb.so
[ 54%] Built target javatinyb
[ 56%] Building Java objects for HelloTinyB.jar
[ 58%] Generating CMakeFiles/HelloTinyB.dir/java_class_filelist
[ 60%] Creating Java archive HelloTinyB.jar
[ 60%] Built target HelloTinyB
[ 62%] Building Java objects for Notification.jar
[ 64%] Generating CMakeFiles/Notification.dir/java_class_filelist
[ 66%] Creating Java archive Notification.jar
[ 66%] Built target Notification
[ 68%] Building Java objects for AsyncTinyB.jar
[ 70%] Generating CMakeFiles/AsyncTinyB.dir/java_class_filelist
[ 72%] Creating Java archive AsyncTinyB.jar
[ 72%] Built target AsyncTinyB
[ 74%] Building CXX object examples/CMakeFiles/checkinit.dir/checkinit.cpp.o
[ 76%] Linking CXX executable checkinit
[ 76%] Built target checkinit
[ 78%] Building CXX object examples/CMakeFiles/hellotinyb.dir/hellotinyb.cpp.o
[ 80%] Linking CXX executable hellotinyb
[ 80%] Built target hellotinyb
[ 82%] Building CXX object examples/CMakeFiles/esstinyb.dir/esstinyb.cpp.o
[ 84%] Linking CXX executable esstinyb
[ 84%] Built target esstinyb
[ 86%] Building CXX object examples/CMakeFiles/uuid.dir/uuid.cpp.o
[ 88%] Linking CXX executable uuid
[ 88%] Built target uuid
[ 90%] Building CXX object examples/CMakeFiles/list_mfg.dir/list_mfg.cpp.o
[ 92%] Linking CXX executable list_mfg
[ 92%] Built target list_mfg
[ 94%] Building CXX object examples/CMakeFiles/asynctinyb.dir/asynctinyb.cpp.o
[ 96%] Linking CXX executable asynctinyb
[ 96%] Built target asynctinyb
[ 98%] Building CXX object examples/CMakeFiles/notifications.dir/notifications.cpp.o
[100%] Linking CXX executable notifications
[100%] Built target notifications
**[sj@Eire build]$ sudo make install**
Generating JNI headers..

Warning: The javah tool is planned to be removed in the next major
JDK release. The tool has been superseded by the '-h' option added
to javac in JDK 8. Users are recommended to migrate to using the
javac '-h' option; see the javac man page for more information.

[  6%] Built target tinybjar
[ 32%] Built target tinyb
[ 54%] Built target javatinyb
[ 60%] Built target HelloTinyB
[ 66%] Built target Notification
[ 72%] Built target AsyncTinyB
[ 76%] Built target checkinit
[ 80%] Built target hellotinyb
[ 84%] Built target esstinyb
[ 88%] Built target uuid
[ 92%] Built target list_mfg
[ 96%] Built target asynctinyb
[100%] Built target notifications
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib64/../lib/java/tinyb.jar
-- Installing: /usr/local/lib64/libjavatinyb.so.0.5.1
-- Installing: /usr/local/lib64/libjavatinyb.so.0
-- Installing: /usr/local/lib64/libjavatinyb.so
-- Set runtime path of "/usr/local/lib64/libjavatinyb.so.0.5.1" to ""
-- Up-to-date: /usr/local/include/tinyb.hpp
-- Installing: /usr/local/include/tinyb
-- Installing: /usr/local/include/tinyb/BluetoothAdapter.hpp
-- Installing: /usr/local/include/tinyb/BluetoothUUID.hpp
-- Installing: /usr/local/include/tinyb/BluetoothDevice.hpp
-- Installing: /usr/local/include/tinyb/BluetoothGattCharacteristic.hpp
-- Installing: /usr/local/include/tinyb/BluetoothGattService.hpp
-- Installing: /usr/local/include/tinyb/BluetoothGattDescriptor.hpp
-- Installing: /usr/local/include/tinyb/BluetoothEvent.hpp
-- Installing: /usr/local/include/tinyb/BluetoothException.hpp
-- Installing: /usr/local/include/tinyb/BluetoothObject.hpp
-- Installing: /usr/local/include/tinyb/BluetoothManager.hpp
-- Installing: /usr/local/lib/pkgconfig/tinyb.pc
-- Installing: /usr/local/lib64/libtinyb.so.0.5.1
-- Installing: /usr/local/lib64/libtinyb.so.0
-- Installing: /usr/local/lib64/libtinyb.so
**[sj@Eire build]$**

**Comment by ghost** [comment]
Note, running the examples isn't a problem:

**[sj@Eire build]$ java -Djava.library.path=/usr/local/lib64 -cp examples/java/HelloTinyB.jar:./java/tinyb.jar HelloTinyB "XX:XX:XX:XX:XX:XX"**
The discovery started: true

**Comment by ghost** [comment]
This is the what's happening outside of the IDE from the command line:

[sj@Eire petermalone]$ /usr/java/jdk1.8.0_152/jre/bin/java -Djava.library.path=/usr/local/lib64 -javaagent:/home/sj/projects/tools/idea-IU-172.4343.14/lib/idea_rt.jar=38175:/home/sj/projects/tools/idea-IU-172.4343.14/bin -Dfile.encoding=UTF-8 -classpath /usr/java/jdk1.8.0_152/jre/lib/charsets.jar:/usr/java/jdk1.8.0_152/jre/lib/deploy.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/cldrdata.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/dnsns.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/jaccess.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/jfxrt.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/localedata.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/nashorn.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/sunec.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/sunjce_provider.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/sunpkcs11.jar:/usr/java/jdk1.8.0_152/jre/lib/ext/zipfs.jar:/usr/java/jdk1.8.0_152/jre/lib/javaws.jar:/usr/java/jdk1.8.0_152/jre/lib/jce.jar:/usr/java/jdk1.8.0_152/jre/lib/jfr.jar:/usr/java/jdk1.8.0_152/jre/lib/jfxswt.jar:/usr/java/jdk1.8.0_152/jre/lib/jsse.jar:/usr/java/jdk1.8.0_152/jre/lib/management-agent.jar:/usr/java/jdk1.8.0_152/jre/lib/plugin.jar:/usr/java/jdk1.8.0_152/jre/lib/resources.jar:/usr/java/jdk1.8.0_152/jre/lib/rt.jar:/home/sj/projects/code/yeelightbedside/target/classes:/home/sj/.m2/repository/org/sputnikdev/bluetooth-manager-tinyb/1.2/bluetooth-manager-tinyb-1.2.jar:/home/sj/.m2/repository/org/sputnikdev/bluetooth-manager/1.3/bluetooth-manager-1.3.jar:/home/sj/.m2/repository/org/sputnikdev/bluetooth-utils/1.9/bluetooth-utils-1.9.jar:/home/sj/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar:/home/sj/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/home/sj/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar:/home/sj/projects/code/yeelightbedside/src/main/lib/tinyb.jar com.petermalone.App
Exception in thread "main" java.lang.RuntimeException: Native library is out of date. Please update the native library.
	at tinyb.BluetoothManager.getBluetoothManager(BluetoothManager.java:317)
	at com.petermalone.App.main(App.java:16)

**Comment by ghost** [comment]
FYI for anyone else this was an issue with maven.

Update your pom with the following:

```
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
</properties>


<build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.6.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
    </plugins>
</build>
