### ISSUE TITLE
Read & Write Value fail

### ISSUE THREAD

**Issue by yongnan0809** [intel-iot-devkit/tinyb#65]
Hello. 

I re flashed  my Edison and updated tinyB and upgrade success.
Maybe something I forget setting when I read value or write value the errot show on.

tinyb.BluetoothException: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "ReadValue" with signature "a{sv}" on interface "org.bluez.GattCharacteristic1" doesn't exist

        at tinyb.BluetoothGattCharacteristic.readValue(Native Method)
        at Notification.main(Notification.java:395)

tinyb.BluetoothException: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "WriteValue" with signature "aya{sv}" on interface "org.bluez.GattCharacteristic1" doesn't exist

        at tinyb.BluetoothGattCharacteristic.writeValue(Native Method)
        at Notification.main(Notification.java:411)

What should I have do ??
any body have idea?

Thank you.

**Comment by yongnan0809** [comment]
I tried to follow https://github.com/intel-iot-devkit/tinyb/issues/47#issuecomment-250087072.

Install the BlueZ 5.43 and Glib2.44. But the problem didn't gone. 
It display same problem.

`root@edison:~# bluetoothctl --version
5.43`

`root@edison:~# ls /usr/lib/ | grep glib
glib-2.0
libdbus-glib-1.la
libdbus-glib-1.so
libdbus-glib-1.so.2
libdbus-glib-1.so.2.2.2
libglib-2.0.la
libglib-2.0.so
libglib-2.0.so.0
libglib-2.0.so.0.4000.0
libglib-2.0.so.0.4400.1
libpyglib-2.0-python.la
libpyglib-2.0-python.so
libpyglib-2.0-python.so.0
libpyglib-2.0-python.so.0.0.0
`
And the build log 

`root@edison:~/tinyb/build# cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILDJAVA=ON
-- The C compiler identification is GNU 4.9.1
-- The CXX compiler identification is GNU 4.9.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28")
-- checking for module 'glib-2.0>=2.40'
--   found glib-2.0, version 2.44.1
-- checking for module 'gio-2.0>=2.40'
--   found gio-2.0, version 2.44.1
-- checking for module 'gio-unix-2.0>=2.40'
--   found gio-unix-2.0, version 2.44.1
INFO - libtinyb Version 0.5.0-8-g6e580f4
-- Found Java: /usr/java/bin/java (found version "1.8.0.101")
-- Found JNI: /usr/java/jre/lib/i386/libjawt.so
-- JNI_INCLUDE_DIRS=/usr/java/include;/usr/java/include/linux;/usr/java/include
-- JNI_LIBRARIES=/usr/java/jre/lib/i386/libjawt.so;/usr/java/jre/lib/i386/client/libjvm.so
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/root/tinyb/build
`

Please help me.

**Comment by yongnan0809** [comment]
I tried to follow #47 (comment).

Install the BlueZ 5.43 and Glib2.44. But the problem didn't gone.
It display same problem.

root@edison:~# bluetoothctl --version
5.43

root@edison:~# ls /usr/lib/ | grep glib
glib-2.0
libdbus-glib-1.la
libdbus-glib-1.so
libdbus-glib-1.so.2
libdbus-glib-1.so.2.2.2
libglib-2.0.la
libglib-2.0.so
libglib-2.0.so.0
libglib-2.0.so.0.4000.0
libglib-2.0.so.0.4400.1
libpyglib-2.0-python.la
libpyglib-2.0-python.so
libpyglib-2.0-python.so.0
libpyglib-2.0-python.so.0.0.0

root@edison:~/tinyb/build# cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILDJAVA=ON
-- The C compiler identification is GNU 4.9.1
-- The CXX compiler identification is GNU 4.9.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28")
-- checking for module 'glib-2.0>=2.40'
--   found glib-2.0, version 2.44.1
-- checking for module 'gio-2.0>=2.40'
--   found gio-2.0, version 2.44.1
-- checking for module 'gio-unix-2.0>=2.40'
--   found gio-unix-2.0, version 2.44.1
INFO - libtinyb Version 0.5.0-8-g6e580f4
-- Found Java: /usr/java/bin/java (found version "1.8.0.101")
-- Found JNI: /usr/java/jre/lib/i386/libjawt.so
-- JNI_INCLUDE_DIRS=/usr/java/include;/usr/java/include/linux;/usr/java/include
-- JNI_LIBRARIES=/usr/java/jre/lib/i386/libjawt.so;/usr/java/jre/lib/i386/client/libjvm.so
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/root/tinyb/build

Please help me.

**Comment by yongnan0809** [comment]
OK. Finally I solved problem use latest committed version tinyB.
https://codeload.github.com/intel-iot-devkit/tinyb/zip/d9c777bc576b5365c2064d55fe872f272faa92e8
